config/routes.rb
Durham::Application.routes.draw do
  root "sessions#new" 

  # users 
  get "sign_up" => "users#new", :as => "sign_up"
  
  # sessions 
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  resources :sessions
  resources :plants
  resources :users do 
  	resources :addresses
  end
end

app/models/address.rb
class Address < ActiveRecord::Base

	validates :address_1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true
end

app/models/plant.rb
class Plant < ActiveRecord::Base
	before_create :set_area_volume 


	def set_area_volume
		self.area = length * width
		self.volume = area * height
	end 

	validates :name, presence: true, uniqueness: true
	validates :length, presence: true
	validates :width, presence: true
	validates :height, presence: true 
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sessions
	has_many :addresses

	# security 
	has_secure_password

	validates :user_email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :user_first_name, presence: true
	validates :user_last_name, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def new 
		@address = Address.new
	end

	def create 
		@address = Address.new(address_params)

		if @address.save
			redirect_to [current_user, @address], notice: 'Address Created'
		else
			redirect_to new_address_path, notice: 'Address Not Saved'
		end
	end

	def show 
		@address = Address.find(params[:id])
	end

	private

		def address_params
			params.require(:address).permit(:address_1, :address_2, :city, :state, :zip)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  helper_method :current_user

  private 

  	# return current user or nothing 
	def current_user
		@current_user ||= User.find_by_user_email(session[:user_email]) if session[:user_email]
	end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
	def new 
		@plant = Plant.new
	end

	def create 
		@plant = Plant.new(plant_params)

		if @plant.save 
			redirect_to @plant, notice: 'Plant Created'
		else
			redirect_to new_plant_path, notice: 'Plant Not Created'
		end
	end

	def show 
		@plant = Plant.find(params[:id])
	end

	def index 
		@plants = Plant.all
	end

	private 

		def plant_params
			params.require(:plant).permit(:name, :length, :width, :height, :area, :volume, :description)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		#no initialization required
	end

	def index 
	end 

	def create 
		# get the user based on user email 
		@user = User.find_by_user_email(params[:user_email])

		# authenticate the user 
		if @user && @user.authenticate(params[:password])
			# set the session user_email
			session[:user_email] = @user.user_email

			# set the session log in time 
			session[:log_in_time] = Time.now

			# user#show
			redirect_to user_path(@user), notice: "Logged in!"
		else
			#back to home 
			redirect_to root_url, notice: "Fail - Not Logged In"
		end
	end

	def destroy
		@session =  Session.new(:user_id => current_user.id, 
								:log_in_time => session[:log_in_time],
								:log_out_time => Time.now)

		# log out either way
		# save session if possible 
		if @session.save		
			# no active user 
			session[:user_email] = nil 

			# back to home 
			redirect_to root_url, notice: "Session Saved - Logged Out!"
		else 
			# no active user 
			session[:user_email] = nil 

			# back to home 
			redirect_to root_url, notice: "Session Did Not Save - Logged Out!"
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :validate_user, only: [:edit, :update, :destroy] 
	before_filter :check_exists, only: [:create]

	def index 
		# send to login page 
		redirect_to root_url
	end

	def new 
		@user = User.new
	end 

	def edit 
		@user = User.find(params[:id])
	end

	def create 
		@user = User.new(user_params)

		if @user.save 
			session[:user_email] = @user.user_email
			redirect_to user_path(@user)
		else 
			redirect_to 'new'
		end
	end 

	def show 
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to root_url, notice: "User is No Longer"
	end

	private 
		def user_params 
			# whitelist password and password_confirmation, keep has hand salt safe 
			params.require(:user).permit(:user_email, :user_first_name, :user_last_name, :password, :password_confirmation)
		end

		# validate current_user 
		def validate_user
			@user = User.find(params[:id])
			if @user == current_user
				# we good
			else
				redirect_to root_url
			end
		end

		def check_exists
			if User.exists?(user_email: params[:user][:user_email])
				redirect_to log_in_path, notice: "Already Have Account - Log In"
			else
				# n/a
			end
		end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_address.html.erb
<div class="address">
	<p>
		<%= @address.address_1 %> <br>
		<%= @address.address_2 %> <br>
		<%= @address.city %> , <%= @address.state %> , <%= @address.zip %> <br>
	</p>
</div>

app/views/addresses/_form.html.erb
<%= form_for [current_user, @address] do |f| %> 
	<%= f.error_messages %>
	<p>
		<%= f.label :address_1 %>
		<%= f.text_field :address_1 %>
	</p>
	<p>
		<%= f.label :address_2 %>
		<%= f.text_field :address_2 %>
	</p>
	<p>
		<%= f.label :city %>
		<%= f.text_field :city %>
	</p>
	</p>
		<%= f.label :state %> 
		<%= f.text_field :state %>
	</p>
	</p>
		<%= f.label :zip %> 
		<%= f.text_field :zip %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %> 

app/views/addresses/new.html.erb
<h1> Create New Address </h1>

<%= render 'form' %>

app/views/addresses/show.html.erb
<h1> Address Details </h1>

<%= render @address %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Durham</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<header>
	<table class="nav">
			<tr>
				<% if current_user %> 
					<th> <%= link_to current_user.user_email, user_path(current_user) %> </th>
					<th> <%= link_to "Sign Out", log_out_path %> </th>
					<th> <%= link_to "New Address", new_user_address_path(current_user) %> </th>
					<th> <%= link_to "All Plants", controller: 'plants', action: 'index' %> </th>
				<% else %>
					<th> <%= link_to "Sign In", log_in_path %> </th>
					<th> <%= link_to "Sign Up", sign_up_path %> </th>
				<% end %>
			</tr>
		</table>	
</header>
<body>
	<div class="flash-messages">
		<% unless flash.empty? %>
			Flash Messages: 
			<% flash.each do |name, msg| -%>
				<%= content_tag :div, msg, class: name %>
			<% end %> 
		<% end %>
	</div>	
	<div class="floating">
		Future Admin Options: <br>
		<th> <%= link_to "New Plant", new_plant_path %> </th>
	</div>

<%= yield %>

</body>
</html>

app/views/plants/_form.html.erb
<%= form_for @plant do |f| %> 
	<%= f.error_messages %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :length %>
		<%= f.number_field :length %>
	</p>
	<p>
		<%= f.label :width %>
		<%= f.number_field :width %>
	</p>
	<p>
		<%= f.label :height %>
		<%= f.number_field :height %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area  :description %> 
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %> 

app/views/plants/_plant.html.erb
<div class="plant">
	<p> 
		Name: <%= @plant.name %> <br>
		Length: <%= @plant.length %> <br>
		Width: <%= @plant.width %> <br>
		Area: <%= @plant.area %> <br>
		Volume: <%= @plant.volume %> <br>
	</p>
<div> 

app/views/plants/index.html.erb
<h1> Plant Index </h1> 

<table> 
	<tr>
		<th> Name </th>
		<th> Length </th>
		<th> Width </th>
		<th> Height </th>
		<th> Area </th>
		<th> Volume </th>
		<td> </th>
	</tr>

	<% @plants.each do |plant| %>
		<tr>
			<td> <%= plant.name %> </td>
			<td> <%= plant.length %> </td>
			<td> <%= plant.width %> </td>
			<td> <%= plant.height %> </td>
			<td> <%= plant.area %> </td>
			<td> <%= plant.volume %> </td>
			<td> <%= link_to "Show Plant", plant_path(plant) %> </td>
		</tr>
	<% end %>
</table>

app/views/plants/new.html.erb
<h1> New Plant </h1>

<%= render 'form' %>

app/views/plants/show.html.erb
<h1> Plant Details </h1>

<%= render @plant %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %> 
	<%= f.error_messages %>
	<p>
		<%= f.label :user_email %>
		<%= f.text_field :user_email %>
	</p>
	<p>
		<%= f.label :user_first_name %>
		<%= f.text_field :user_first_name %>
	</p>
	<p>
		<%= f.label :user_last_name %>
		<%= f.text_field :user_last_name %>
	</p>
	</p>
		<%= f.label :password %> 
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field  :password_confirmation %> 
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %> 

app/views/users/_user.html.erb
<p>
	<%= user.user_first_name %> <%= user.user_last_name %> at <%= user.user_email %> <br>

</p>

<%= link_to 'Edit User', edit_user_path(user) %>

app/views/users/edit.html.erb
<h1> Edit User </h1>  

<%= render 'form' %> 

<%= link_to 'Delete User', user_path(@user), method: :delete, data: {confirm: 'Wanna be no longer?'} %>

app/views/users/new.html.erb
<h1> New User </h1> 

<%= render 'form' %> 

app/views/users/show.html.erb
<h1> User </h1> 

<%= render @user %>